scriptsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls',namespace='store'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .import views

app_name='store'

urlpatterns = [
    path('', views.all_scripts,name='all_scripts'),
    path('home',views.home,name='home'),
    path('<slug:genre_slug>',views.genre_items,name='genre_items'),
    path('script/<slug:slug>',views.script_details,name='script_details'),
    path('register/',views.register_page,name='register_page'),
    path('search/',views.search_box,name='search_box'),
    path('login/',views.login_page,name='login_page'),
    path('logout/',views.signout,name='signout'),
    path('scripts/',views.script_list,name='script_list'),
    
]

store/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = 'Genres'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("store:genre_items", args=[self.slug])


SCRIPT_CATEGORY = (

    ('M', 'Movie'),
    ('S', 'Short Film'),
    ('D', 'Documentry'),
    ('T', 'Series')
)
MOVIE_CERTIFICATE = (
    ('U', 'U'), ('U/A', 'U/A'), ('A', 'A')
)


class Script(models.Model):
    title = models.CharField('Title ', max_length=50)
    director = models.CharField('Director', max_length=580)
    writer = models.CharField(max_length=2050)
    cast = models.CharField('Casts', max_length=2000)
    genre = models.ManyToManyField("Genre")
    rating = models.FloatField()
    verdict = models.CharField(max_length=50)
    poster = models.ImageField(upload_to='posters')
    pdf = models.FileField(upload_to='pdf')
    recommended = models.BooleanField(default=True)
    category = models.CharField(
        choices=SCRIPT_CATEGORY, default='Movie', max_length=150)
    certificate = models.CharField(
        choices=MOVIE_CERTIFICATE, default='U/A', max_length=50)
    summary = models.TextField()
    slug = models.SlugField()
    year = models.PositiveIntegerField()
    language = models.CharField(max_length=50)
    award_winner = models.BooleanField(default=False)

    class Meta:

        verbose_name_plural = 'Scripts'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("store:script_details", args=[self.slug])

class MovieSearch(models.Model):
    name_of_movie=models.CharField(max_length=150)
    def __str__(self):
        return self.name_of_movie
    

store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import MovieSearch

class MovieSearchForm(forms.ModelForm):
    name_of_movie=forms.CharField(max_length=150,widget=forms.TextInput(attrs={
        'class':'form-control me-2','placeholder':'Enter Movie Title'
    }))
    class Meta:
       model=MovieSearch
       fields='__all__'




class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length = 100, widget = forms.TextInput(attrs={
        'class' : 'form-control', 'placeholder': 'Enter Username'
    }))

    email=forms.CharField(max_length=100, required=False,widget=forms.EmailInput(attrs={
        'class':'form-control','placeholder':'Enter Email'
    }))
    password=forms.CharField(max_length=100, required=True,widget=forms.PasswordInput(attrs={
        'class':'form-contol','placeholder':'Enter Password'
    }))
    password1=forms.CharField(max_length=100, required=True,widget=forms.PasswordInput(attrs={
        'class':'form-control','placeholder':'Confirm Password'
    }))
    
    class Meta:
        model = User
        fields=['username','email','password','password1',]

store/views.py
from django.shortcuts import get_object_or_404, render, redirect
from . models import Script, Genre, MovieSearch
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm,MovieSearchForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from rest_framework.response import Response
from .serializers import ScriptSerializer
from rest_framework.parsers import JSONParser
from rest_framework.renderers import JSONRenderer
from rest_framework.decorators import api_view, renderer_classes
from django.views.decorators.csrf import csrf_exempt


def home(request):
    recommended = Script.objects.filter(recommended=True)
    return render(request, 'store/home.html', {'recommended': recommended})


def all_scripts(request):
    scripts = Script.objects.all()
    return render(request, 'store/all_scripts.html', {'scripts': scripts})


def genre_items(request, genre_slug):
    genre = get_object_or_404(Genre, slug=genre_slug)
    scripts = Script.objects.filter(genre=genre)
    return render(request, 'store/genre_items.html', {'scripts': scripts})

@login_required(login_url='store:login_page')
def script_details(request, slug):
    scripts = Script.objects.get(slug=slug)
    script_genre = scripts.genre.first()
    similar_movies = Script.objects.filter(genre__name__endswith=script_genre)

    return render(request, 'store/script_details.html', {'scripts': scripts, 'similar_movies': similar_movies})


def register_page(request):
        if request.method=="POST":
                username=request.POST['name']
                email=request.POST['email']
                password=request.POST['password']
                password1=request.POST['password1']
                user=User.objects.create_user(username=username,email=email,password=password)
                user.save()
                return redirect('store:login_page')
        else:
                return render(request,'store/register.html')


def login_page(request):
        if request.method == "POST":
                username = request.POST.get('username')
                password = request.POST.get('password')
                user = authenticate(request, username=username, password=password)
                if user is not None:
                        login(request, user)
                        return redirect('store:home')
                else:
                        messages.info(request, 'Invalid Details')
        return render(request,'store/login.html',{})


def signout(request):
    context = {}
    logout(request)
    context['error'] = "You have been logged out"
    return render(request, 'store/login.html', context)

def search_box(request):
        searched_movies = Script.objects.filter(title__icontains = request.POST.get('name_of_movie',None))
        return render(request, 'search_book.html', {'searched_movies':searched_movies})


@api_view(('GET',))
@csrf_exempt
def script_list(request):
        if request.method=="GET":
                scripts=Script.objects.all()
                serializer=ScriptSerializer(scripts,many=True)
                return Response(serializer.data)
        elif request.method=="POST":
               data=JSONParser().parser(request)
               serializer=ScriptSerializer(data=data)
               if serializer.is_valid():
                       serializer.save()
                       return Response(serializer.data)
               return Response(serializer.errors,status=400)

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Document</title>
    {% endblock %}
    
    <link rel = 'stylesheet' href ="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel = 'stylesheet' href ="{% static 'css/style.css' %}">
    <link rel = 'stylesheet' href ="{% static 'css/register.css' %}">
    <link rel = 'stylesheet' href ="{% static 'css/style.css' %}">
    <link rel = 'stylesheet' href ="{% static 'css/home.css' %}">
    <link rel = 'stylesheet' href ="{% static 'css/script_details.css' %}">
    <link rel = 'stylesheet' href = "{% static 'uikit/css/uikit.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    
</head>
<body style="background-color: black">

  <nav class="navbar navbar-expand-lg navbar-dark uk-background-blend-hue:blue">
    <div class="container-fluid">
      <div id = 'logo'>
        <img src = "{% static 'img/moviescript.jpg' %}">
      </div>
      <!-- <a class="navbar-brand" href="#">Navbar</a> -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" >
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'store:all_scripts' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'store:home' %}">Recommended</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" style="color:white">{{genre.name}}</a>
            </li>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      {% if user.is_authenticated %}
      <div class="dropdown">
       <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
         Hello {{user.username}}
      
       <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
         <li><a class="dropdown-item" href="#">Upload Photo</a></li>
         <li><a class="dropdown-item" href="{% url 'store:signout' %}">Logout</a></li>
       </ul>
     </div> 
    </button>
     {% else %}
      <a class="nav-link" href="{% url 'store:register_page' %}">
          <button type="button" class="btn btn-outline-primary">Sign Up</button></a>
        <a class="nav-link" href="{% url 'store:login_page' %}">
            <button type="button" class="btn btn-outline-success">Login</button>
          </a>
     {% endif %}
      </div>
      </div>
      <form class="d-flex" method = 'GET' action = "{% url 'store:search_box' %}" style="margin: 0px;">
        <!-- <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"> -->
        {% csrf_token %}
        {{search_form.name_of_book}}
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </nav>
  
  <p uk-margin style = "width: auto; margin: auto; margin-top: auto; background-color:black">                                                                                                 
    {% for genre in genres %}
      <a class="uk-button uk-button-default" href="{{genre.get_absolute_url}}" style="color:goldenrod"><strong>{{genre.name}}</strong></a>
      {% endfor %}
  </p>     
  



{% block content %}

{% endblock %}







      
    <footer align='center' style="color: darkgreen">
        <h4 ><strong>Download and Feel the born of your favourite characters</strong></h4>
    </footer>
   
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    
</body>
</html> 

templates/store/all_scripts.html
{% extends 'base.html' %}
{% block title %}
<title>Homepage</title>
{% endblock %}
{% block content %}
<div class = 'container'style = "padding-left: 0px">
    <div class = 'row'>
    {% for script in scripts %}
    <div class = 'col- col-sm-4 col-md-4 col-lg-3 col-xl-2'>
          
                
    <div>
        <div class="uk-card uk-card-default uk-card-body"> 
            <a href="{{script.get_absolute_url}}">
         
            <img src="{{script.poster.url}}" width="25%" height="55%">
        </a>         
      
         </div>
        </div>
              
            </a>
        </div>
      
    {% endfor %}
    </div>
    </div>
    
{% endblock %}

templates/store/genre_items.html
{% extends 'base.html' %}
{% block title %}
<title>Homepage</title>
{% endblock %}
{% block content %}
<div class = 'container'style = "padding-left: 0px">
    <div class = 'row'>
    {% for script in scripts %}
    <div class = 'col- col-sm-4 col-md-4 col-lg-3 col-xl-2'>
          
                
    <div>
        <div class="uk-card uk-card-default uk-card-body"> 
         <a href="{{script.get_absolute_url}}"> 
            <img src="{{script.poster.url}}" width="25%" height="55%">
</a>
                 
         </div>
         
        </div>
              
            </a>
        </div>
      
    {% endfor %}
    </div>
    </div>
    
{% endblock %}

templates/store/home.html
{% extends 'base.html' %}

{% block title %}
<title>Script Port | Home</title>
{% endblock %}
{% block content %}
<div class='container'>
  <div class='row' align='center'>
    <h1 style="color: gold">Recommended Movies</h1>
  </div>
  <div class='row'>

    {% for script in recommended %}


    <div class='col-6 col-sm-4 col-md-4 col-lg-3 col-xl-2'>


      <div class="uk-card uk-card-default uk-card-body">
        <a href="{{script.get_absolute_url}}">
        <img class="card-img-top" src="{{script.poster.url}}" width="20%" height="45%" responsive>
        </a>
       
      </div>
    </div>
      {% endfor %}
    
  </div>
</div>
</div>
</div>
{% endblock %}

templates/store/login.html
{% extends "base.html" %}
{% load static  %}

{% block title %}
  <title>Script Hub|Login</title>
{% endblock %}
{% block content %}
  <div class="container">
      
      <form action="{% url 'store:login_page' %}" method="POST">
          {% csrf_token %}
          <div id="form-control" style="color: darkgreen">
              <label>Username</label>
              <input type="text" name="username" class="form-control" placeholder="Enter Username" maxlength="50" required> 
          </div>
          <div id="form-control">
          <label>Password</label>
          <input type="password" name="password" class="form-control" placeholder="Enter Passwords" required>
          </div>
          {% for message in messages %}
          <p class="successMsg">{{message}}</p>
          {% endfor %}
          <div id="haveAnAccount">
              <p>Don't have an account ?</p></br>
          </br> <a href="{% url 'store:register_page' %}" ><strong>Register</strong></a>
          </div>
          <button type="submit" href="#" id="submitButton">Login</button>
        </form>
        </div>
  
  
{% endblock %}

templates/store/register.html
{% extends 'base.html' %}
{% block title %}
<title>Script Hub/Register</title>
{% endblock%}
{% block content %}
<div id="container">
    <div class="header">
        <h1>Create Account</h1>
    </div>
    <form ation="{% url 'store:register_page'%}" method="post">
        {% csrf_token %}
        <div id="form-control">
            <label>Username</label>
            <input name='name' class="form-control" type="text"  required>
        </div>
    
        <div id="form-control">
            <label>Email</label>
            <input name='email' class="form-control" type="email" required>
        </div>
       
        <div id="form-control">
            <label>Password</label>
            <input name='password' class="form-control" id="password" type="password" onkeyup='check();' required>
        
    </div>
        <div id="form-control">
            <label>Confirm Password</label>
            <input name='password1' id="confirm_password" class="form-control" type="password"  onkeyup='check();' required>
            <span id='message'></span>
            {{register_form.errors}}
           
               <p>Already Have an Account</p>
                <div id="haveAnAccount">
                <a href="{% url 'stor e:login_page' %}"><strong>Login</strong></a>
            </div>
            <button type="submit" id="submitButton">Register</button>
        </div>
    </form>
    
</div>
<script>
var check = function(){

  if (document.getElementById("password").value ==
      document.getElementById("confirm_password").value){
      document.getElementById('message').style.color= 'green';
      document.getElementById('message').innerHTML='Matching';
      }else{
        document.getElementById('message').style.color='red';
        document.getElementById('message').innerHTML='Not Matching';
      }

}



</script>
{% endblock %}

templates/store/script_details.html
{% extends 'base.html' %}

{% block title %}
<title>{{scripts.title}} </title>
{% endblock %}

{% block content %}

<div class='container' style='border: 2px solid black; width: 80%'>
    <div class='row' style='border: 2px solid black'>
        <div class='col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4'>

            <div id='imageContainer'>
                <img src="{{scripts.poster.url}}">
            </div>
        </div>
        <div class='col-10 col-sm-9 col-md-3 col-lg-5 col-xl-6' >
            <div id='summaryContent'>
                <table>
                <h1 style="color: teal">{{scripts.title}}</h1>
                <th><h2>Directed by: <strong>{{scripts.director}}</strong></h2></th>
                <h2>Written by: <strong>{{scripts.writer}}</strong></h2>
                <h2>Genre: <br /><strong>{{scripts.genre.all|join:"," }}</strong><br /></h2>
                <h3>Casts</h3>
                <h3>{{scripts.cast}}</h3>
                <h3>Synopsis:</h3>
                <h4>{{scripts.summary}}</h4>
                <h3>Rating:</h3>
                <h4>{{scripts.rating}}</h4>

            </table>
            <a href="{{scripts.pdf.url}}" download="{{scripts.pdf.url}}">
                <button id='download'>
                    Download PDF
                    <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="black"
                        class="bi bi-download" viewBox="0 0 16 16">
                        <path
                            d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
                        <path
                            d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
                    </svg>
                </button>
                </a>
            </div>
        </div>
    </div>
</div>


<div class='container'>
    <div class='row'>
        <h4>Similar Movies</h4>
    </div>
    <div class='row'>
        {% for similar_movie in similar_movies %}
        <div class='col-6 col-sm-4 col-md-4 col-lg-3 col-xl-2'>
           
            
           <a href="{% url  'store:script_details' similar_movie.slug %}">
                <div>
                    <div class="uk-card uk-card-default uk-card-body">
                        <img src="{{similar_movie.poster.url}}">

                    </div>
                </div>
            </a>
           
        </div>
        {% endfor %}

    </div>

</div>
{% endblock %}

templates/store/searchbox.html
{% extends "base.html" %}
{% block title %}
<title>ScriptHub|Search Box</title>
{% endblock %}
{% block content %}
<div class = 'container'>
    <div class = 'row'><h4>Searched Movies</h4></div>
    <div class = 'row'>
        {% if search_movie % }
        {% for movies in search_movie %}
        <div class = 'col-6 col-sm-4 col-md-4 col-lg-3 col-xl-2'>
                <a href = "">
                  <div>
                    <div class="uk-card uk-card-default uk-card-body"> 
                        <img src = "{{movies.cover_image.url}}">
                       
                    </div>
                </div>
              </a>
              </div>
            {% endfor %}
        { % else %}
        <div class = 'row'>
                <h3>Book Not Available! Check Back Later</h3>
            </div>
        {% endif %}

  
{% endblock %}